name: goreleaser

on:
  push:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Make All
        run: |
          chmod +x package.sh
          ./package.sh

      - name: Upload Release Asset
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release/

      - name: Stash all changes
        run: |
          git stash

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean --release-notes=./Release.md

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
